apiVersion: v1
kind: Service
metadata:
  name: pages-service
  labels:
    name: pages-service
    app: php-pages
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: php
    tier: frontend